version: "3.9"

services:
  backend:
    build:
      context: ./Spotify-Backend
      dockerfile: Dockerfile
    container_name: spotify-backend
    ports:
      - "8080:8080"
    env_file:
      - ./Spotify-Backend/.env
    networks:
      - spotify-net

  frontend:
    build:
      context: ./spotify-frontend
      dockerfile: Dockerfile
    container_name: spotify-frontend
    ports:
      - "3000:80"
    env_file:
      - ./spotify-frontend/.env
    depends_on:
      - backend
    networks:
      - spotify-net

networks:
  spotify-net:
