version: "3.9"

services:
  backend:
    build:
      context: ./Spotify-Backend
      dockerfile: Dockerfile
    container_name: spotify-backend
    ports:
      - "127.0.0.1:9090:9090"
    env_file:
      - ./Spotify-Backend/.env
    networks:
      - spotify-net

  frontend:
    build:
      context: ./spotify-frontend
      dockerfile: Dockerfile
    container_name: spotify-frontend
    ports:
      - "127.0.0.1:8080:80"
    env_file:
      - ./spotify-frontend/.env
    depends_on:
      - backend
    networks:
      - spotify-net

networks:
  spotify-net:
